### ISSUE TITLE
Does not run on PI Zero 

### ISSUE THREAD

**Issue by popeyesfx** [wonkyto/homenetmon#1]
Have tried your container for telegraf and it does not run on a PI Zero w which is a arm32v6 arch.
Is there something I need to do to get it to work.

thanks

**Comment by wonkyto** [comment]
Hi, Popeyesfx,

I'm sorry I don't have a Pi Zero to test. 

I'm surprised it doesn't work because the docker image was built on a Raspberry Pi 3b, which is the same arch (arm32v6).

You could attempt to build your own docker image from https://github.com/wonkyto/homenetmon/blob/master/Dockerfiles/telegraf/Dockerfile.

**Comment by popeyesfx** [comment]
Hi Dave

Thanks for the reply, i dont think the 3b uses v6 as its a quad core
processor ( cortex a53 ) if i remember right and they are v7 instruction
set.
the zeros are single core . The problem will be that the images for the
quad core units will be using the v7 instruction set that wont run on the
zero.

I come across this alot, as most of my projects are zero based

cheers for the reply

jack
